version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  install-and-test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3.10 tests.py
workflows:
  test:
    jobs:
      - install-and-test